#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-weld-parent
Version  : 15
Release  : 2
URL      : https://github.com/weld/parent/archive/15.tar.gz
Source0  : https://github.com/weld/parent/archive/15.tar.gz
Source1  : https://repo1.maven.org/maven2/org/jboss/weld/weld-parent/6/weld-parent-6.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-weld-parent-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-weld-parent package.
Group: Data

%description data
data components for the mvn-weld-parent package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jboss/weld/weld-parent/6
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/jboss/weld/weld-parent/6


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/jboss/weld/weld-parent/6/weld-parent-6.pom
